version: "2"

services:
    api:
        image: LouisTrezzini/projet-mairie
        volumes:
            - api-data:/uploads:rw
            - api-logs:/logs:rw
        ports:
            - "127.0.0.1:5000:8000"
        restart: always

volumes:
    api-data:
        driver: local
    api-logs:
        driver: local
