version: "2"

services:
    api:
        build: api
        volumes:
            - api-data:/data/api:rw
        ports:
            - "127.0.0.1:5000:5000"
        restart: always

volumes:
    api-data:
        driver: local
