version: "2"

services:
    api:
        image: ltrezzini/franceocr-api
        build: api
        volumes:
            - api-data:/uploads:rw
        ports:
            - "127.0.0.1:5000:5000"
        restart: always

volumes:
    api-data:
        driver: local
