version: "2"

services:
    api:
        build: api
        volumes:
            - api-data:/data/api:rw
        ports:
            - "127.0.0.1:3030:3030"
        restart: always

volumes:
    api-data:
        driver: local
